export const BOOK_ADD_ROOM_FAIL = 'BOOK_ADD_ROOM_FAIL';
export const BOOK_ADD_ROOM = 'BOOK_ADD_ROOM';
export const BOOK_REMOVE_ROOM = 'BOOK_REMOVE_ROOM';
export const BOOK_SAVE_HOTEL_RESERVATION = 'BOOK_SAVE_HOTEL_RESERVATION';
export const BOOK_SAVE_MORE_INFORMATION = 'BOOK_SAVE_MORE_INFORMATION';
export const BOOK_EMPTY = 'BOOK_EMPTY';