export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST';
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS';
export const BOOKING_CREATE_FAIL = 'BOOKING_CREATE_FAIL';
export const BOOKING_CREATE_RESET = 'BOOKING_CREATE_RESET';
export const BOOKING_DETAILS_REQUEST = 'BOOKING_DETAILS_REQUEST';
export const BOOKING_DETAILS_SUCCESS = 'BOOKING_DETAILS_SUCCESS';
export const BOOKING_DETAILS_FAIL = 'BOOKING_DETAILS_FAIL';
export const BOOKING_MINE_LIST_REQUEST = 'BOOKING_MINE_LIST_REQUEST';
export const BOOKING_MINE_LIST_SUCCESS = 'BOOKING_MINE_LIST_SUCCESS';
export const BOOKING_MINE_LIST_FAIL = 'BOOKING_MINE_LIST_FAIL';

export const BOOKING_COMPLETE_REQUEST = 'BOOKING_COMPLETE_REQUEST';
export const BOOKING_COMPLETE_SUCCESS = 'BOOKING_COMPLETE_SUCCESS';
export const BOOKING_COMPLETE_FAIL = 'BOOKING_COMPLETE_FAIL';
export const BOOKING_COMPLETE_RESET = 'BOOKING_COMPLETE_RESET';

export const BOOKING_LIST_REQUEST = 'BOOKING_LIST_REQUEST';
export const BOOKING_LIST_SUCCESS = 'BOOKING_LIST_SUCCESS';
export const BOOKING_LIST_FAIL = 'BOOKING_LIST_FAIL';

export const BOOKING_DELETE_REQUEST = 'BOOKING_DELETE_REQUEST';
export const BOOKING_DELETE_SUCCESS = 'BOOKING_DELETE_SUCCESS';
export const BOOKING_DELETE_FAIL = 'BOOKING_DELETE_FAIL';
export const BOOKING_DELETE_RESET = 'BOOKING_DELETE_RESET';
